### ISSUE TITLE
Be more flexible around inputting rate limits

### ISSUE THREAD

**Issue by cornerstone-programming** [BenFradet/RiotSharp#557] opened 2018-06-16 13:32 UTC
Hello together,

I really love this project!

I just run into an issue regulary:
503 - Service not available

The reason might be:

The rate limits in RiotSharp are based on 10s / 10min. (based on documentation)

At least for my Development API Riot have rates per 1s and per 2min:

![image](https://user-images.githubusercontent.com/31933721/41499009-dd3fbb66-7179-11e8-8c02-2e23d28b6eb9.png)

Have a great weekend

Tom

**Comment by JanOuborny** [comment] 2018-06-16 14:39
If you get an 503 error. It's not caused by your application reaching the rate limit. Instead Riot's api servers are probably failing to respond to your request.

**Comment by cornerstone-programming** [comment] 2018-06-16 14:49
Ouh okay thanks!
I gonna work on this.
Still I got this mismatch of documentation of RiotSharp and Riot's limits.

**Comment by cornerstone-programming** [comment] 2018-06-16 14:57
Yeah - Now I run into 429, Rate Limit Exceeded

**Comment by BenFradet** [comment] 2018-06-16 21:36
good point, we should be more flexible at RiotSharp's level when providing those limits

**Comment by cornerstone-programming** [comment] 2018-06-16 22:29
Just found out: in the response header you can find the limits:
`{
    **"X-App-Rate-Limit-Count": "1:1,1:120",**
    "Content-Encoding": "gzip",
    "X-Method-Rate-Limit-Count": "1:60",
    "Vary": "Accept-Encoding",
    "Connection": "keep-alive",
    **"X-App-Rate-Limit": "20:1,100:120",**
    "X-Method-Rate-Limit": "2000:60",
    "transfer-encoding": "chunked",
    "X-NewRelic-App-Data": "PxQFWFFSDwQTV1hXBggCUlwTGhE1AwE2QgNWEVlbQFtcC2VOchRAFgtba04hJmweQxEMD1hfUhRJRwUeBQMXIEkxTQ9VV1pXQStYDFRDH1JKBhtRSFMKBQhcV1QHBBtLVR0UCgdWAFNUBA1aDQ1VVwRVX0MdB1IOF1Nq",
    "Date": "Sat, 16 Jun 2018  12:28:04 GMT",
    "Content-Type": "application/json;charset=utf-8"
}`

**Comment by JanOuborny** [comment] 2018-06-17 10:07
Actually you can provide your own limits. Use the correct method overload for this: `RiotApi.GetInstance(string apiKey, IDictionary<TimeSpan, int> rateLimits, ICache cache)`

**Comment by BenFradet** [comment] 2018-06-18 09:22
Good point @JanOuborny , closing :+1:

**Closed by BenFradet** 2018-06-18 09:22 UTC
Labels: question
