### ISSUE TITLE
GetMatch() includingTimline parsing bug

### ISSUE THREAD

**Issue by briedrice** [BenFradet/RiotSharp#407] opened 2017-05-28 03:47 UTC
I was working with the getMatch method and keep getting a bad request '400'
I think the region enum needs updated. 

in V3 the na values and a couple others are different. 

this is the call i was making below:

myApi.GetMatch(Region.na, 2510454764);

right now the region.na = 'na' but i think its 'na1'.

I'm just a junior dev, so Please correct me if I am wrong.

**Comment by JanOuborny** [comment] 2017-05-28 10:25
RiotSharp currently calls the v2.2 match endpoint, because it is not migrated to v3. Therefore, it uses the region based domains and the old url format (e.g. https://na.api.riotgames.com/api/lol/NA/v2.2/match/2510454764), which uses the region identifier `na` and not the platform identifier `na1`.

Furthermore, I could not reproduce your issue in the develop branch by using your parameters. This could be an issue in the current release.

**Comment by JanOuborny** [comment] 2017-05-28 10:33
Ok, I found the problem. When using the `includeTimeline` parameter it parses the bool parameter into a `True` or `False`. This however causes a bad request. The correct values must be `true` and `false`.

**Comment by JanOuborny** [comment] 2017-05-28 13:29
Closing, resolved in #409

**Closed by JanOuborny** 2017-05-28 13:29 UTC
Labels: bug, in progress
