### ISSUE TITLE
GetMatchList throws exception

### ISSUE THREAD

**Issue by tpercario** [BenFradet/RiotSharp#568] opened 2018-07-16 17:13 UTC
This exception occurs when GetMatchList is called with only the necessary parameters (all others are left to default):

Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Error setting value to 'Season' on 'RiotSharp.MatchEndpoint.MatchReference'.
  Source=Newtonsoft.Json
Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.

**Comment by JanOuborny** [comment] 2018-07-19 17:48
Could you give us the provided parameters?

**Comment by tpercario** [comment] 2018-07-20 01:29
This is the call that throws the exception.

The parameters that were passed are:
region = RiotSharp.Misc.Region.na
Summoner = "Professor Lumps"

var summoner = api.GetSummonerByName(region, Summoner);

**Comment by JanOuborny** [comment] 2018-07-20 17:47
Looking at your method calls, you are not using the latest build. This bug might be fixed in the latest version, because I cannot reproduce it. [Create a NuGet package of the latest code version](https://github.com/BenFradet/RiotSharp#build-your-own-latest-nuget-package)

**Closed** 2019-04-10 20:34 UTC
Labels: bug
